# 用Koa2+mysql来做简单的服务端

## 写在前面
一直想用`koa2 + MySQL`来进行服务端的开发，就是没时间。最近终于开始了这个搁置已久的计划，这篇文章对这个过程做个简单的记录。

## 介绍
这个项目是个比较直观而且基础的项目, 用于一些中小型项目的开发或者是自己的练手是没问题。`MySQL`也采用的是非常直白的`sql`语句进行操作。主要是也想加深对`MySQL`的理解，想换成`Sequelize`的话也很简单。下面进入我们正题。

## 文件结构介绍

本项目是通过`koa-generator`创建的工程，非常的简单。希望对`koa`了解更深一点的朋友可以自己尝试着手动搭建一下，也不是很麻烦。下面是经过改造之后的文件目录结构。

```js
koa-shop-api
│   config                  // 配置文件 包括 日志/项目配置
│   middlewares             // koa中间件
│   models                  // 静态文件
│   public                  // koa2保留文件（后来会删除）
└───routes                  // API抛出曾/ controller层
│   │   index               // route自动注入文件
└───service                 // 业务逻辑层（承上启下， 操作models为controller层服务）
└───sql                     // MySQL帮助层
│   │   sql_file            // sql文件
│   │   async.js            // 数据库同步脚本文件
│   │   index.js            // MySQL 使用SQL语句
│   │   utils               // 工具类
│   │   validators          // 验证器
│   │   views               // koa2保留文件（后来会删除）
│   app.js                  // koa初始化
│   main.js                 //  项目启动文件

```

## 简化入口文件

这个很简单， 我只是把`www`中的内容都集中到了`main.js`中。 而且把中间价都拆分了出来



## 增加配置文件

配置文件全部都在`config`文件夹 

这里主要是抽离了系统的配置，配置文件使用的`yaml`文件。不了解的朋友可以看一下[介绍]()

`config.dev.yaml`
```yaml
#######项目名称#######
projectName: koa-shop-api
#######备注
remark: null
#######正式/测试 production or develop
env: development
#######Node启动端口
nodeport: 3001

#######Session Key
session_key: session_id
#######Session Secret
sessionSecret: secretCat
#######Session Timeout
sessionTimeout: 30 * 60 * 1000

#######OSS配置 Start
#OSS Key
#OSS Secret
#######OSS配置 End
#########Momgo配置 Start
#########数据库配置 Start
#DB config
DB:
  host: 'localhost' # 这也是注释，不会输出的
  port: 3306
  database: 'project_progress'
  user: 'root'
  password: '123456'
#正式mongo地址
#DB_CONN_STR: 'mongodb://localhost:27017/BookPlatform'
#########数据库配置配置 End

#######Http参数 Start
#Rest链接地址 以HTTP开头

#######Http参数 End

#demokey:1

### Http通信地址的配置
#serverPath: "http://172.16.100.116:30062/"

#######请求参数配置
safe_path: "urlPath"
safe_body: "urlBody"
#######请求白名单（配置的URL不进行加密和解密）支持*，如：/ABCD/*
safe_filter_url: ['/login', '/reg']
#######安全模块配置 End
```

配置文件基本包括了我们所有的不同环境的配置，然后通过`index.js`中的`confman`进行解析。

`index.js`
```js
const confman = require('confman')

const mode = process.env.NODE_ENV === 'production' ? 'prod' : 'dev'
const configPath = `${__dirname}/config.${mode}`
const config = confman.load(configPath)
module.exports = config
```

使用方式也很简单， 直接通过引用`config`文件夹就可以引入对象形式的配置，就像下面一样。

` main.js`
```js
const config = require('./config')
// 服务端口号
const serverPort =  config.nodeport || 3000
```

## 改造自带route

## 错误处理

关于错误处理，一开始处理的不是很好，到处都是`try catch`，后来导致在使用的时候越来越不顺手。所以最近刚刚，重构了异常处理相关的模块。

### `controller`层(重点)

`router`层比较特殊，是面向外部的核心， 而且`ctx`贯穿整个`router`层。所以比较重要。首先我们要了解`koa2`中的错误处理机制

`Koa`本身通过事件来监听和捕获错误，默认情况下，`koa`将所有错误输出到 `stderr`，除非 `app.silent` 为 `true`。 当 `err.status` 是 `404` 或 `err.expose` 是 `true` 时默认错误处理程序也不会输出错误。

```js
app.on("error",(err,ctx)=>{//捕获异常记录错误日志
   console.log(new Date(),":",err);
});
```

但是如果中间件中采用了`try catch`来捕捉错误，那么`app.on("error")`将无法监听到，这个时候需要我们手动激活
```js
try {
  // ..todo
} catch(e) {
  // 需要手动的激活
  this.app.emit('error', e, this);
}
```

了解了`koa`自己的机制之后下面我们开始进行改造

- 第一步：定义错误常量
  
这个没什么好讲的， 就是好管理一些
```js
/*
 * @Author: etongfu
 * @Email: 13583254085@163.com
 * @LastEditors: etongfu
 * @Description: Error code 常量
 * @youWant: add you want info here
 * @Date: 2019-03-14 17:39:42
 * @LastEditTime: 2019-03-20 15:13:18
 */
//错误message
module.exports.ERROR_MSG = Object.freeze({
  [-1]: "查询无数据",
  400: 'invalid param',
  401: 'unauthorized',
  403: 'forbidden',
  404: 'not found',
  500: 'internal server error',
  503: 'service busy',
  1001: 'some custom error msg'
})
// 错误常量
module.exports.CONSTANTS = Object.freeze({
  // http级别的错误
  HTTP_CODE: {
    BAD_REQUEST: 400,               // BAD_REQUEST 参数错误
    UNAUTHORIZED: 401,              // 请求未授权： (Unauthorized)
    FORBIDDEN: 403,                 // 拒绝访问
    NOT_FOUND: 404,                 // 404
    INTERNAL_SERVER_ERROR: 500,     // 服务错误
    SERVICE_BUSY: 503               // 服务器繁忙
  },
  // 可以理解为service 错误
  CUSTOM_CODE: {
    EMPTY_RESULT: -1,               // 查询无数据
    SESSION_FAILURE: -2,            // session超时
    OPERATE_ERROR: -3,              // 操作失败
    SOME_CUSTOM_ERROR: 1001         // catch到error       
  }
})
```

- 第二步：实现自定义的错误类

在这里我们把错误类型分为两类`CustomError, HttpError`
`CustomError` ==> 自定义异常
`HttpError`   ==> Http异常

```js
/*
 * @Description: Error构造器
 * @youWant: add you want info here
 * @Date: 2019-03-15 15:28:29
 * @LastEditTime: 2019-03-15 16:23:17
 */
const {ERROR_MSG,  CONSTANTS} = require('./constants')
const HTTP_CODE = CONSTANTS.HTTP_CODE
/**
 * 通用类型的判断
 */
class CustomError extends Error {
  constructor (code, msg) {
    this.super()
    this.code = code
    this.msg =  msg || ERROR_MSG[code] || 'unknown error'
  }
  getCodeMsg () {
    return {
      code,
      msg
    }
  }
}
// http 请求错误
class HttpError extends CustomError {
  constructor (code, msg) {
    if (Object.values(HTTP_CODE).indexOf(code) < 0) {
      throw Error('not an invalid http code')
    }
    this.super(code, msg)
  }
}
module.exports = {CustomError, HttpError}
```
- 第三步：创建错误处理中间件

这里主要是用来捕获和错误和返回值

```js
/*
 * @Description: 错误处理中间件
 * @youWant: add you want info here
 * @Date: 2019-03-14 15:58:42
 * @LastEditTime: 2019-03-20 16:22:37
 */
const {CustomError, HttpError} = require('../error')
const LoggerUtil = require ('../utils/logger')
const ReturnMessage = require('../utils/message')
const returnMessage = new ReturnMessage()
/**
 * controller 错误统一处理
 * @param {*} err 
 * @param {*} ctx 
 */
const ctxErrorHandle  = (ctx, next) => {
    return next().catch((error) => {
        // 默认错误
        let code = 500
        let msg = 'unknown error'
        // 使用 throw new CustomError() 或者 throw new HttpError() 抛出的异常
        if (error instanceof CustomError || error instanceof HttpError) {
          const res = error.getCodeMsg()
          ctx.status = error instanceof HttpError ? res.code : 200
          code = res.code
          msg = res.msg
        } else {
          //通过ctx.throw() 抛出的错误 此时 (error instanceof Error) = true  
          /**
           * ctx.throw(400, 'name required') 等效于:
           * const err = new Error('name required');
           * err.status = 400;
           * err.expose = true;
           * throw err;
           */
          code = error.status
          msg = error.message
        }
        LoggerUtil.logError(ctx,error, 0)
        // 发送错误信息给前端
        ctx.body = returnMessage.setErrorResult(code, msg)
    })
}

module.exports = ctxErrorHandle
```

- 第四步：注意事项
  
1. 由于独特的洋葱模型，注册中间件的时候要在第一步注册错误处理中间件，这样错误中间件就可以对应用程序进行兜底。
2. 在route层中,不用再使用`try catch`
3. 通过`ctx.throw(xxx, 'xxx')` 和 `throw new CustomError(xxx, 'xxx)`都可以让中间件捕获。


### service层和dao层

这两层现在还没找到什么特别好的方式，主要是用`try catch`处理

`sevice`层

```js
async _getExistUserByOptions (optionName, optionValue) {
    let result = false
    try {
      result = await userModel.findOneUserByOption(optionName, optionValue)
    } catch (error) {
      logger.error(`ServiceError: error in UserService _isUserAlreadyExistByPhone, ${error}`)
      result = []
    }
    return result
  }
```
`dao` 层
```js
/**
 * 创建用户
 * @param {*} user 
 */
async createUser (user) {
  let result 
  try {
    result = await dbUtils.insertData(tables.USERS_TABLE, user)
  } catch (error) {
    logger.error(error)
    result = null
  }
  return result
}
```

